name: Check Composer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add HTTP basic auth credentials
      run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
    - name: Install drupal
      uses: php-actions/composer@v5
      with:
        command: create-project drupal/recommended-project drupal
