name: Check Drupal Dockerizer basic functionality

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cache Composer dependencies from improve speed
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Get Drupal Project repository
      uses: actions/checkout@v2
      with:
        repository: 'drupal/recommended-project'
        path: './'

    - name: Add HTTP basic auth credentials for composer
      run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

    - name: Run composer install
      uses: php-actions/composer@v5
      with:
        command: install --ignore-platform-reqs

    - name: Run composer update
      uses: php-actions/composer@v5
      with:
        command: update --ignore-platform-reqs

    - name: Get Drupal Dockerizer repository
      uses: actions/checkout@v2
      with:
        repository: 'jet-dev-team/drupal-dockerizer'
        path: '.drupal-dockerizer'

    - name: Create basic config.yml
      run: |
        echo "---" > drupal-dockerizer.yml
        echo "" >> drupal-dockerizer.yml
        echo "compose_project_name: drupal-project" >> drupal-dockerizer.yml
        echo "user_uid: $(id -u)" >> drupal-dockerizer.yml
        echo "user_gid: $(id -g)" >> drupal-dockerizer.yml
        echo "drupal_root_dir: $GITHUB_WORKSPACE" >> drupal-dockerizer.yml

    - name: Run main playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Run drush-commands playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: drush-commands.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Check drupal
      run: curl http://localhost | grep "Drupal"
      
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: http://localhost
        devices: iPhone 6,iPhone 6 landscape
        noDesktop: false
        
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
        
    - uses: actions/upload-artifact@v2
      with:
        path: ".drupal-dockerizer/drupal-project/data/mysql"
        name: database

